launch:
    job_name: # Name of the job
    run_dir: # Where to save the job script/logs
    activate_env_cmd: # Command to activate the python environment
checkpointing:
    save: # Where to save the checkpoints
    load: ${checkpointing.save}
data:
    data_path: # List of paths to the data
    tokenizer_model: # Path to the tokenizer
